### ISSUE TITLE
uiZeroclipConfig overrides previous configuration

### ISSUE THREAD

**Issue by afilgueira** [lisposter/angular-zeroclipboard#13]
Hi guys, first of all, nice work!

Regarding my issue, I'm working with ruby & angular, so I've added zeroclipboard to my project using zeroclipboard-rails. In this case, the ruby gem makes all the configuration magic. I'd like to avoid setting again the configuration, so I've made a workaround. 

It would be great if you can add an option to choose what to do in that case. I can submit a PR with this change if you want to.

Thanks!

**Comment by lisposter** [comment]
Hi @afilgueira , I am not familiar with ruby and rails, if you think this is great, just send a PR, it's cool :beers:
